name: Deploy-To-Server

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploying:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout of the repo
        uses: actions/checkout@v2

      - name: Deploy to production server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          fingerprint : ${{secrets.DEV_KEY}}
          
          script: |
            cd ${{ secrets.PATH }}
            php artisan down
            php artisan view:clear
            php artisan config:clear
            php artisan route:clear
            php artisan cache:clear
            git stash
            git pull git@github.com:lelotz/whitemark.git main
            /opt/cpanel/composer/bin/composer update --no-interaction --prefer-dist --optimize-autoloader
            php artisan optimize:clear
            php artisan up
